### ISSUE TITLE
Forked your OS

### ISSUE THREAD

**Issue by Samson666** [sk-io/os#1]
Hi!
As i mentioned before, i made a fork of your OS. I named it **QuadOS** because this name is
free of royalty and it sounds cool :rofl: 
You can find it at [https://github.com/Samson666/QuadOS](url).
I added a discussion forum and a wiki page to it.
You are more than wellcome to leave a little comment at the forum :heart: 

I stopped developing my own os because it is a lot of (writing)work.
I'd like to go your code to get more understanding about it and add more comments in my code.

Johannes

**Comment by sk-io** [comment]
Alright, cool!
